root: true
env:
  browser: true
  commonjs: true
  es2022: true
  jest: true
  node: true
extends:
  - eslint:all
ignorePatterns:
  - playground/
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 2 #
  quotes:
    - error
    - single #
  semi:
    - error
    - never #
